rspec-branch
m15e/Enumerables pull request #3
Opened 2020-08-04 16:00 UTC by m15e

new branch because workflows isn't working for some reason

- [ ] Rspec tests for Enumerable methods

2020-08-04 18:43 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for that first step into RSpec.
However, there are some changes to need to be done

1. I got this error when I ran `rspec`
```rb
$ rspec spec/enumerables_spec.rb 

An error occurred while loading ./spec/enumerables_spec.rb. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'enumerable'

LoadError:
  cannot load such file -- enumerable
# ./spec/enumerables_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00004 seconds (files took 0.48227 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

2. Read the comments left below

Kindly make the changes and submit a new code review request.
Thanks

Mael FOSSO

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
Check if it's an Enumerator

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
Check if it's an Enumerator

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
Check if it's an Enumerator

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
Check for pattern, String or Integer, ...

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
What about testing if all the array contains only one value

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +    end
Also, add test for empty or falsy array

2020-08-04 18:43 UTC, maelfosso commented on spec/enumerables_spec.rb
> +  end
Write for operation like `:+` and/or `:*`

2020-08-05 12:32 UTC, mcrd25 approved these changes
# Changes Approved :heavy_check_mark: 


Hi Team! :wave: 

Good job with changers, all test pass! :+1: 



***If you have any questions, now or in the future, do not hesitate to contact me on social media, email or on slack and I will be glad to chat with you.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

2020-08-05 14:11 UTC, merged